[tools]
uv = "latest"

[env]
_.python.venv = { path = ".venv" }
_.file = ".env"
PYTHONPATH = "./src"

[tasks.setup]
run = '''
[ -f .env ] || cp .env.example .env
uv sync
# uv run pre-commit install
uv run python -m src.kaggle.write submission-code
'''

[tasks.dl-comp]
description = '''
Download Kaggle competition dataset.
Comptition name is set in environment variable KAGGLE_COMPETITION_NAME
'''
run = "uv run python -m src.kaggle.download competition-dataset"

[tasks.up-code]
description = "Upload source code to Kaggle dataset."
run = "uv run python -m src.kaggle.upload codes"

[tasks.up-art]
description = "Upload artifacts to Kaggle model."
run = "uv run python -m src.kaggle.upload artifacts"

[tasks.meta-deps]
description = "Create metadata for Kaggle code that installs dependencies."
run = "uv run python -m src.kaggle.write deps-metadata"

[tasks.up-sourec]
description = "Upload codes and artifacts to Kaggle."
run = "uv run python -m src.kaggle.upload sources"

[tasks.meta-sub]
description = "Create metadata for Kaggle submission code."
run = "uv run python -m src.kaggle.write submission-metadata"

[tasks.push-deps]
description = "Push Kaggle code that installs dependencies."
run = '''
uv run python -m src.kaggle.write deps-metadata
cd codes/deps
uv run kaggle k push
cd ../..
'''

[tasks.push-sub]
description = "Push Kaggle submission code."
run = '''
uv run python -m src.kaggle.check nessesary-artifacts-exist
uv run python -m src.kaggle.upload codes
cd codes/submission
uv run kaggle k push
cd ../..
'''

[tasks.fmt]
description = "Run pre-commit formatting."
run = "uv run pre-commit run --all-files"
