name: Push Kaggle Dependencies

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "codes/deps/requirements.txt"

jobs:
  push-deps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv pip install tyro nbformat pydantic kaggle
        env:
          UV_SYSTEM_PYTHON: 1

      - name: Push dependencies to Kaggle
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
          KAGGLE_COMPETITION_NAME: ${{ secrets.KAGGLE_COMPETITION_NAME }}
          UV_SYSTEM_PYTHON: 1
        run: make push-deps
