name: Push Kaggle Dependencies

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "codes/deps/requirements.txt"
  workflow_dispatch:

jobs:
  push-dependencies:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Create virtual environment and install dependencies
        run: |
          uv venv --python 3.11
          uv pip install tyro pydantic pydantic-settings python-dotenv kaggle nbformat

      - name: Push Kaggle dependencies code
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
          KAGGLE_COMPETITION_NAME: ${{ secrets.KAGGLE_COMPETITION_NAME }}
        run: |
          source .venv/bin/activate
          python -m src.kaggle_utils.write deps-metadata
          python -m src.kaggle_utils.write deps-code
          if [ ! -f codes/deps/code.ipynb ]; then
              echo "code.ipynb not found in codes/deps. Skipping push."
              exit 0
          fi
          cd codes/deps && kaggle k push && cd ../..
