name: Push Kaggle Submission

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  push-submission:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Create virtual environment and install dependencies
        run: |
          uv venv --python 3.11
          uv pip install tyro pydantic pydantic-settings python-dotenv kaggle nbformat

      - name: Push Kaggle submission
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
          KAGGLE_COMPETITION_NAME: ${{ secrets.KAGGLE_COMPETITION_NAME }}
        run: |
          source .venv/bin/activate
          python -m src.kaggle_utils.check nessesary-artifacts-exist
          python -m src.kaggle_utils.upload codes
          sleep 30
          cd codes/submission
          kaggle k push
          cd ../..
