name: Python CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  lint-test-and-check:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv pip install ruff mypy pytest pydantic pydantic-settings
        env:
          UV_SYSTEM_PYTHON: 1

      - name: Run ruff lint
        run: uv run ruff check --output-format=github .

      - name: Run ruff format
        run: uv run ruff format --check --diff

      - name: Run mypy
        run: uv run mypy .

      - name: Run pytest
        run: uv run pytest
